In [4]:
import pandas as pd
df = pd.read_csv("sales.csv",index_col="Unnamed: 0")
df

,CompPrice,Income,Advertising,Population,Price,ShelveLoc,Age,Education,Urban,US,high
1,138,73,11,276,120,Bad,42,17,Yes,Yes,yes
2,111,48,16,260,83,Good,65,10,Yes,Yes,yes
3,113,35,10,269,80,Medium,59,12,Yes,Yes,yes
4,117,100,4,466,97,Medium,55,14,Yes,Yes,no
5,141,64,3,340,128,Bad,38,13,Yes,No,no
...,...,...,...,...,...,...,...,...,...,...,...
396,138,108,17,203,128,Good,33,14,Yes,Yes,yes
397,139,23,3,37,120,Medium,55,11,No,Yes,no
398,162,26,12,368,159,Medium,40,18,Yes,Yes,no
399,100,79,7,284,95,Bad,50,12,Yes,Yes,no
400,134,37,0,27,120,Good,49,16,Yes,Yes,yes

In [13]:
#---------------------------------------------------------
x_cont= df[df.columns[[0,1,2,3,6]]]

from sklearn.preprocessing import StandardScaler
SS = StandardScaler()
SS_X = SS.fit_transform(x_cont)
SS_X = pd.DataFrame(SS_X)
SS_X
SS_X.columns = list(df.columns[[0,1,2,3,6]])
SS_X

     CompPrice    Income  Advertising  Population       Age
0     0.850455  0.155361     0.657177    0.075819 -0.699782
1    -0.912484 -0.739060     1.409957   -0.032882  0.721723
2    -0.781896 -1.204159     0.506621    0.028262  0.350895
3    -0.520720  1.121336    -0.396715    1.366649  0.103677
4     1.046337 -0.166631    -0.547271    0.510625 -0.947000
..         ...       ...          ...         ...       ...
395   0.850455  1.407551     1.560513   -0.420131 -1.256023
396   0.915749 -1.633482    -0.547271   -1.547909  0.103677
397   2.417512 -1.526151     0.807733    0.700853 -0.823391
398  -1.630719  0.370022     0.054953    0.130170 -0.205346
399   0.589279 -1.132606    -0.998939   -1.615848 -0.267150

[400 rows x 5 columns]

In [14]:
from sklearn.preprocessing import LabelEncoder
LE = LabelEncoder()
SS_X["ShelveLoc"] = LE.fit_transform(df["ShelveLoc"])
SS_X["Urban"]     = LE.fit_transform(df["Urban"])
SS_X["US"]        = LE.fit_transform(df["US"])
SS_X["high"]      = LE.fit_transform(df["high"])
SS_X["Education"]      = LE.fit_transform(df["Education"])
SS_X.head()

,CompPrice,Income,Advertising,Population,Age,ShelveLoc,Urban,US,high,Education
0,0.850455,0.155361,0.657177,0.075819,-0.699782,0,1,1,1,7
1,-0.912484,-0.739060,1.409957,-0.032882,0.721723,1,1,1,1,0
2,-0.781896,-1.204159,0.506621,0.028262,0.350895,2,1,1,1,2
3,-0.520720,1.121336,-0.396715,1.366649,0.103677,2,1,1,0,4
4,1.046337,-0.166631,-0.547271,0.510625,-0.947000,0,1,0,0,3

In [15]:
X=SS_X
y=df.Price

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [34]:
from sklearn.neighbors import KNeighborsRegressor
knn=KNeighborsRegressor(n_neighbors=12)
knn.fit(X_train,y_train)

train_acc=knn.score(X_train,y_train)
test_acc=knn.score(X_test,y_test)

train_acc,test_acc

(0.37652286147827096, 0.23009854373839356)

In [32]:
from sklearn.model_selection import GridSearchCV
model3=KNeighborsRegressor()
params={
    "n_neighbors":range(1,41)
}

grid=GridSearchCV(model3,param_grid=params)
grid.fit(X_train,y_train)

GridSearchCV(estimator=KNeighborsRegressor(),
             param_grid={'n_neighbors': range(1, 41)})

In [35]:
grid.best_score_

np.float64(0.21362969335627593)

In [36]:
grid.best_params_

{'n_neighbors': 18}